#!/bin/bash

##### Port Number1: 4000
##### Port Number2: 4001
##### Time Zone: Etc/UTC
##### Version: latest
##### AppData Path: /pg/appdata/firefox
##### shm size: 1gb

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

docker run -d \
  --name=--name="${app_name}"\
  --security-opt seccomp=unconfined `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ="${time_zone}"\
  -e FIREFOX_CLI=https://www.linuxserver.io/ `#optional` \
  -p "${port_number1}":3000 \
  -p "${port_number2}":3001 \
  -v "${appdata_path}":/config \
  --shm-size="${shm_size}" \
  --restart unless-stopped \
  lscr.io/linuxserver/firefox:"${latest}"

# Verify the Docker container is running
docker ps | grep "$app_name"
