#!/bin/bash

##### Port Number: 4700
##### Port Two: 4699
##### AppData Path: /pg/appdata/firefox
##### Version Tag: latest
##### Time Zone: America/New_York
##### FirefoxCLI URL: https://www.linuxserver.io
##### Shm Size: 1gb

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      --security-opt seccomp=unconfined \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -e FIREFOX_CLI="${firefoxcli_url}" \
      -p "${port_number}":3000 \
      -p "${port_two}":3001 \
      -v "${appdata_path}":/config \
      --shm-size="${shm_size}" \
      --restart unless-stopped \
      lscr.io/linuxserver/firefox:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}

# Function usage example:
# deploy_container
