#!/bin/bash

##### Port Number: 9117
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/jackett
##### PathTo Blackhole: /pg/downloads/
##### Auto Update: true 
##### Version Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -e AUTO_UPDATE="${auto_update}" \
      -e RUN_OPTS= `#optional` \
      -p "${port_number}":9117 \
      -v "${appdata_path}":/config \
      -v "${pathto_blackhole}":/downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/jackett:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
