#!/bin/bash

##### Port Number: 8686
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/lidarr
##### Music Path: /pg/media/music
##### ClientDownload Path: /pg/downloads
##### Version Tag: latest
##### Expose:

deploy_container() {

    # Sourcing and configuration file - required
    source /pg/scripts/apps_support.sh "$app_name"
    source "$config_path"
    config_path="/pg/config/${app_name}.cfg"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${expose}""${port_number}":8686 \
      -v "${appdata_path}":/config \
      -v "${music_path}":/music \
      -v "${clientdownload_path}":/downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/lidarr:"${version_tag}"
    
    # display app deployment information
    appverify
}
