#!/bin/bash

# Source the configuration file to get the appdata_path
source /pg/config/$app_name.cfg

# Deploy Netdata with the updated paths
docker run -d --name="$app_name" \
  -p 19999:19999 \
  -v netdataconfig:"${appdata_path}" \
  -v netdatalib:"${appdata_path}/netdatalib" \
  -v netdatacache:"${appdata_path}/var/cache" \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata
