#!/bin/bash

##### Port Number: 19999
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/netdata
##### Version Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"
    
    # Deploy Netdata with the updated paths
    docker run -d --name="${app_name}" \
      -p "${port_number}":19999 \
      -v "${appdata_path}"/netdataconfig:/etc/netdata \
      -v "${appdata_path}"/netdatalib:/var/lib/netdata \
      -v "${appdata_path}"/netdatacache:/var/cache/netdata \
      -v /etc/passwd:/host/etc/passwd:ro \
      -v /etc/group:/host/etc/group:ro \
      -v /proc:/host/proc:ro \
      -v /sys:/host/sys:ro \
      -v /etc/os-release:/host/etc/os-release:ro \
      --cap-add SYS_PTRACE \
      --security-opt apparmor=unconfined \
      netdata/netdata:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
