#!/bin/bash

##### Port Number: 6789
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/nzbget
##### Download Path: /pg/downloads/nzbget
##### User Name: nzbget 
##### User Password: tegbzn6789
##### Version Tag: latest

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -e NZBGET_USER="${user_name}" `#optional` \
      -e NZBGET_PASS="${user_password}" `#optional` \
      -p "${port_number}":6789 \
      -v "${appdata_path}":/config \
      -v "${download_path}":/downloads \
      --restart unless-stopped \
      nzbgetcom/nzbget:${version_tag}
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
