#!/bin/bash

##### Port Number: 4600
##### Port Two: 4599
##### AppData Path: /pg/appdata/opera
##### Version Tag: latest
##### Time Zone: America/New_York
##### OperaCLI URL: https://www.linuxserver.io
##### Shm Size: 1gb 

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      --security-opt seccomp=unconfined \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -e OPERA_CLI="${operacli_url}" \
      -p "${expose}""${port_number}":3000 \
      -p -p "${expose}""${port_two}":3001 \
      -v "${appdata_path}":/config \
      --shm-size="${shm_size}" \
      --restart unless-stopped \
      lscr.io/linuxserver/opera:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}

# Function usage example:
# deploy_container
