#!/bin/bash

##### Port Number: 5055
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/overseerr
##### Version Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${port_number}":5055 \
      -v "${appdata_path}":/config \
      --restart unless-stopped \
      lscr.io/linuxserver/overseerr:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
