#!/bin/bash

##### AppData Path: /pg/appdata/plex_debrid

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

# Configuration Paths
config_path="/pg/config/plex_debrid"
app_name="plex_debrid"

# Run the Docker container with the specified settings
echo "Running the itstoggle/plex_debrid Docker container..."
docker run -d \
  --name="${app_name}" \
  --network=host \
  -v "${config_path}:/config" \
  --restart unless-stopped \
  itstoggle/plex_debrid

# Verify the Docker container is running
docker ps | grep "$app_name"
