#!/bin/bash

##### AppData Path: /pg/appdata/plex_debrid
##### Port Number: 32400
##### Time Zone: America/New_York
##### Version Tag: latest

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

deploy_container() {
    # Run the Docker container with the specified settings
    docker run -d \
      --name="${app_name}" \
      --network=host \
      -v "${config_path}:/config" \
      --restart unless-stopped \
      itstoggle/plex_debrid:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
