#!/bin/bash

# Default Port: 32400

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

# Prompt the user for the Plex claim key
read -p "Enter your Plex claim key: " CLAIM_KEY

# Set the default Docker image version, appdata location, and timezone
DOCKER_VERSION=${2:-"latest"}
TIMEZONE=${4:-"America/New_York"}

# Ensure the media directory exists
MEDIA_PATH="/pg/media"
mkdir -p $MEDIA_PATH

# Pull the specified version of the Plex Docker image
docker pull plexinc/pms-docker:$DOCKER_VERSION

# Run the Plex Docker container with the specified settings
docker run -d \
  --name="$app_name" \
  --network=host \
  -e PLEX_CLAIM=$CLAIM_KEY \
  -e TZ=$TIMEZONE \
  -v "${appdata_path}":/config \
  -v $MEDIA_PATH:/media \
  -v /etc/localtime:/etc/localtime:ro \
  --restart unless-stopped \
  plexinc/pms-docker:$DOCKER_VERSION

# Verify the Docker container is running
docker ps | grep "$app_name"
