#!/bin/bash

##### AppData Path: /pg/appdata/plex_debrid
##### Port Number: 32400
##### Time Zone: America/New_York
##### Version Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    # Run the Docker container with the specified settings
    docker run -d \
      --name="${app_name}" \
      --network=host \
      -v "${config_path}:/config" \
      --restart unless-stopped \
      itstoggle/plex_debrid:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
