#!/bin/bash

#!/bin/bash

# Specify the config file path
config_path="/pg/config/$1.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

# Prompt the user for the Plex claim key
read -p "Enter your Plex claim key: " CLAIM_KEY

# Set the default Docker image version, appdata location, and timezone
DOCKER_VERSION=${1:-"latest"}
APPDATA_LOCATION=${2:-"/pg/appdata/plex"}
TIMEZONE=${3:-"America/New_York"}

# Ensure the media directory exists
MEDIA_PATH="/pg/media"
mkdir -p $MEDIA_PATH

# Pull the specified version of the Plex Docker image
docker pull plexinc/pms-docker:$DOCKER_VERSION

# Run the Plex Docker container with the specified settings
docker run -d \
  --name=$app_name \
  --network=host \
  -e PLEX_CLAIM=$CLAIM_KEY \
  -e TZ=$TIMEZONE \
  -v "${appdata_path}":/config \
  -v $MEDIA_PATH:/media \
  -v /etc/localtime:/etc/localtime:ro \
  --restart unless-stopped \
  plexinc/pms-docker:$DOCKER_VERSION

# Verify the Docker container is running
docker ps | grep plex
