#!/bin/bash

##### App Name: Prowlarr
##### AppData Path: /pg/appdata/prowlarr
##### Port Number: 9696
##### Time Zone: America/New_York

# Run the Prowlarr Docker container with the specified settings
docker run -d \
  --name=${app_name}" \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=${time_zone}" \
  -p "${port_number}":9696 \
  -v "${appdata_path}":/config \
  --restart unless-stopped \
  lscr.io/linuxserver/prowlarr:latest

# Verify the Docker container is running
docker ps | grep "$app_name"
sleep 1
