#!/bin/bash

##### Port Number: 8080
##### Torrenting Port: 6881
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/qbittorrent
##### Download Path: /pg/downloads/qbittorrent
##### Version Tag: latest
##### Expose:

deploy_container() {

    # Sourcing and configuration file - required
    source /pg/scripts/apps_support.sh "$app_name"
    source "$config_path"
    config_path="/pg/config/${app_name}.cfg"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -e WEBUI_PORT="${port_number}" \
      -e TORRENTING_PORT="${torrenting_port}" \
      -p "${expose}""${port_number}":8080 \
      -p "${torrenting_port}":6881 \
      -p "${torrenting_port}":6881/udp \
      -v "${appdata_path}":/config \
      -v "${download_path}":/downloads `#optional` \
      --restart unless-stopped \
      lscr.io/linuxserver/qbittorrent:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
