#!/bin/bash

##### Port Number: 7878
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/radarr
##### TV Path: /pg/media/tv
##### ClientDownload Path: /pg/downloads

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

docker run -d \
  --name="${app_name}" \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ="${time_zone}" \
  -p "${port_number}":7878 \
  -v "${appdata_path}":/config \
  -v "${tv_path}":/tv \
  -v "${clientdownload_path}":/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/radarr:latest

# Verify the Docker container is running
docker ps | grep "$app_name"
