#!/bin/bash

##### Port Number: 9000
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/sabnzbd
##### Download Path: /pg/downloads/nzbget/downloads/
##### Incomplete Downloads: /pg/downloads/nzbget/incomplete_downloads
##### Version Tag: latest

# Specify the app name and config file path
app_name=$1
config_path="/pg/config/${app_name}.cfg"

# Source the configuration file to get the appdata_path and app_name
if [[ -f "$config_path" ]]; then
    source "$config_path"
else
    echo "Error: Configuration file not found at $config_path."
    exit 1
fi

deploy_container() {
    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${port_number}":8080 \
      -v "${appdata_path}":/config \
      -v "${download_path}":/downloads \
      -v "${incomplete_downloads}":/incomplete-downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/sabnzbd:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
