#!/bin/bash

##### Port Number: 9000
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/sabnzbd
##### Download Path: /pg/downloads/nzbget/downloads/
##### Incomplete Downloads: /pg/downloads/nzbget/incomplete_downloads
##### Version Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${port_number}":8080 \
      -v "${appdata_path}":/config \
      -v "${download_path}":/downloads \
      -v "${incomplete_downloads}":/incomplete-downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/sabnzbd:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
