#!/bin/bash

##### Port Number: 8081
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/sickgear
##### TV Path: /pg/media/tv
##### Download Path: /pg/downloads
##### Version Tag: latest
##### Expose:

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${expose}""${port_number}":8081 \
      -v "${appdata_path}":/config \
      -v "${tv_path}":/tv \
      -v "${download_path}":/downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/sickgear:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}

# Example usage to deploy SickGear
app_name="sickgear"
port_number=8081
time_zone="America/New_York"
appdata_path="/pg/appdata/sickgear"
tv_path="/pg/media/tv"
download_path="/pg/downloads"
version_tag="latest"

deploy_container
