#!/bin/bash

##### Port Number: 8989
##### Time Zone: America/New_York
##### AppData Path: /pg/appdata/sonarr
##### TV Path: /pg/media/tv
##### ClientDownload Path: /pg/downloads
##### Verison Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ="${time_zone}" \
      -p "${port_number}":8989 \
      -v "${appdata_path}":/config \
      -v "${tv_path}":/tv \
      -v "${clientdownload_path}":/downloads \
      --restart unless-stopped \
      lscr.io/linuxserver/sonarr:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
