#!/bin/bash

##### Port Number: 3001
##### AppData Path: /pg/appdata/uptimekuma

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    docker run -d \
      --name="${app_name}" \
      -p "${expose}""${port_number}":3001 \
      -v "${appdata_path}":/app/data \
      --restart=unless-stopped \
      louislam/uptime-kuma:1
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
