#!/bin/bash

##### Port Number: 3001
##### AppData Path: /pg/appdata/uptimekuma
##### Expose: 

deploy_container() {

    # Sourcing and configuration file - required
    source /pg/scripts/apps_support.sh "$app_name"
    source "$config_path"
    config_path="/pg/config/${app_name}.cfg"

    docker run -d \
      --name="${app_name}" \
      -p "${expose}""${port_number}":3001 \
      -v "${appdata_path}":/app/data \
      --restart=unless-stopped \
      louislam/uptime-kuma:1
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
