#!/bin/bash

##### Port Number: 4748
##### AppData Path: /pg/appdata/vaultwarden
##### Signups Enabled: false
##### WebSocket Enabled: false
##### Verison Tag: latest

deploy_container() {

    # Specify config file path and source information
    config_path="/pg/config/${app_name}.cfg"
    source "$config_path"

    # Function to generate a random 16-character admin token (letters a-z and numbers 0-9)
    generate_random_token() {
        tr -dc 'a-z0-9' < /dev/urandom | head -c 16
    }
    
    # Generate a random admin token if it's not already set in the config file
    if [[ -z "$admin_token" ]]; then
        echo "Admin token not found in the config file. Generating a new one."
        admin_token=$(generate_random_token)
        echo "admin_token=$admin_token" >> "$config_path"
    fi

    # Run the Vaultwarden container with the specified settings
    docker run -d \
      --name="${app_name}" \
      -e SIGNUPS_ALLOWED="${signups_allowed}" \
      -e INVITATIONS_ALLOWED="${invitations_allowed}" \
      -e WEBSOCKET_ENABLED="${websocket_enabled}" \
      -e ADMIN_TOKEN="${admin_token}" \
      -p "${port_number}:80/tcp" \
      -v "${appdata_path}:/data:rw" \
      --restart unless-stopped \
      vaultwarden/server:"${version_tag}"
    
    # Verify the Docker container is running
    docker ps | grep "$app_name"
}
