#!/bin/bash

# ANSI color codes
RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
NC="\033[0m" # No color

source /pg/scripts/expose_check.sh

# Other functions...

apps_interface() {
    local app_name=$1
    local config_path="/pg/config/${app_name}.cfg"

    # Other code...

    # Menu
    while true; do
        clear

        # Re-source the config file to refresh values
        source "$config_path"

        check_deployment_status  # Display the initial status
        expose_status=$(check_expose_status "$app_name")
        echo ""
        echo "D) Deploy $app_name"
        echo "A) Appdata Path: $appdata_path"
        echo "P) Port: $port_number"
        echo "C) Config File - Edit"
        echo "K) Kill Docker Container"
        echo "E) Exposed Port: $expose_status"
        echo "Y) Default the Config File"
        echo "Z) Exit"
        echo ""

        read -p "Choose an option: " choice

        case ${choice,,} in  # Convert input to lowercase
            # Other cases...

            c)
                bash /pg/apps/apps_config_edit.sh "$app_name" "$config_path"
                ;;
            # Other cases...

            z)
                break
                ;;
            *)
                echo "Invalid option, please try again."
                read -p "Press Enter to continue..."
                ;;
        esac
    done
}
